OddJobPlatformV1.1/Models/JobProvider.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace OddJobPlatformV1._1.Models
{
    public class JobProvider
    {
        [Key]
        public int jpID { get; set; }
        [Display(Name = "Name")]
        //[Required]
        public string jpName { get; set; }
        //[Required]
        [Display(Name = "User Name")]
        public string userName { get; set; }
       // [Required]
        [Display(Name = "Password")]
        public string password { get; set; }
       // [Required]
        [Display(Name = "Address")]
        public string address { get; set; }
       // [Required]
        [Display(Name = "Email Id")]
        public string email { get; set; }
       // [Required]
        [Display(Name = "Contact Number")]
        public string contactNum { get; set; }
    }


    public class JobProviderDBContext : DbContext
    {
        public JobProviderDBContext()
        {

        }
        public DbSet<JobProvider> JobProviders { get; set; }
    }
}

OddJobPlatformV1.1/Controllers/JobProvidersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OddJobPlatformV1._1.Models;

namespace OddJobPlatformV1._1.Controllers
{
    public class JobProvidersController : Controller
    {
        private JobProviderDBContext db = new JobProviderDBContext();

        // GET: JobProviders
        public ActionResult Index()
        {
            return View(db.JobProviders.ToList());
        }

        // GET: JobProviders/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobProvider jobProvider = db.JobProviders.Find(id);
            if (jobProvider == null)
            {
                return HttpNotFound();
            }
            return View(jobProvider);
        }

        // GET: JobProviders/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: JobProviders/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "jpID,jobName,userName,password,address,email,contactNum")] JobProvider jobProvider)
        {
            if (ModelState.IsValid)
            {
                db.JobProviders.Add(jobProvider);
                db.SaveChanges();
                return RedirectToAction("Login");
            }

            return View(jobProvider);
        }



        // GET: JobProviders/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobProvider jobProvider = db.JobProviders.Find(id);
            if (jobProvider == null)
            {
                return HttpNotFound();
            }
            return View(jobProvider);
        }

        // POST: JobProviders/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "jpID,jobName,userName,password,address,email,contactNum")] JobProvider jobProvider)
        {
            if (ModelState.IsValid)
            {
                db.Entry(jobProvider).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(jobProvider);
        }

        // GET: JobProviders/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            JobProvider jobProvider = db.JobProviders.Find(id);
            if (jobProvider == null)
            {
                return HttpNotFound();
            }
            return View(jobProvider);
        }

        // POST: JobProviders/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            JobProvider jobProvider = db.JobProviders.Find(id);
            db.JobProviders.Remove(jobProvider);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        // GET: JobProviders/Create
        public ActionResult Login()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Login(JobProvider jp)
        {
            using (JobProviderDBContext db = new JobProviderDBContext())
            {
                var cl = db.JobProviders.Single(c => c.email == jp.email && c.password == jp.password);

                if (cl != null)
                {
                    Session["JPId"] = cl.jpID.ToString();
                    Session["jpEmail"] = cl.email.ToString();
                    //Session["jpName"] = cl.jpName.ToString();
                    return RedirectToAction("Index","Jobs");
                }
                else
                {
                    ModelState.AddModelError("", "Wrong");
                }
            }
            return View();
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

OddJobPlatformV1.1/Views/JobProviders/Create.cshtml
@model OddJobPlatformV1._1.Models.JobProvider

@{
    ViewBag.Title = "Create";
}

<h2>Register</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobProvider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.jpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contactNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OddJobPlatformV1.1/Views/JobProviders/Delete.cshtml
@model OddJobPlatformV1._1.Models.JobProvider

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>JobProvider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.jobName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactNum)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

OddJobPlatformV1.1/Views/JobProviders/Details.cshtml
@model OddJobPlatformV1._1.Models.JobProvider

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>JobProvider</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.jobName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.jobName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.userName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.userName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.password)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.password)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.address)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.address)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.contactNum)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.contactNum)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.jpID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

OddJobPlatformV1.1/Views/JobProviders/Edit.cshtml
@model OddJobPlatformV1._1.Models.JobProvider

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>JobProvider</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.jpID)

        <div class="form-group">
            @Html.LabelFor(model => model.jpName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.jpName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.jpName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.userName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.userName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.userName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.password, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.password, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.address, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.address, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.contactNum, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.contactNum, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contactNum, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

OddJobPlatformV1.1/Views/JobProviders/Index.cshtml
@model IEnumerable<OddJobPlatformV1._1.Models.JobProvider>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.jpName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.userName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.password)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.address)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.contactNum)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.jpName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.userName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.password)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.address)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.contactNum)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.jpID }) |
            @Html.ActionLink("Details", "Details", new { id=item.jpID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.jpID })
        </td>
    </tr>
}

</table>

OddJobPlatformV1.1/Views/JobProviders/Login.cshtml
@{
    ViewBag.Title = "Login";
}

<h2>Login</h2>

@model OddJobPlatformV1._1.Models.JobProvider

@using (Html.BeginForm("Login", "JobProviders", FormMethod.Post))
{
    <table border="0" cellpadding="0" cellspacing="0">
        <tr>
            <th colspan="3">
                Login
            </th>
        </tr>
        <tr>
            <td>
                Username
            </td>
            <td>
                @Html.TextBoxFor(model => model.email)
            </td>
            <td>
                @Html.ValidationMessageFor(m => m.email, "", new { @class = "error" })
            </td>
        </tr>
        <tr>
            <td>
                Password
            </td>
            <td>
                @Html.PasswordFor(model => model.password)
            </td>
            <td>
                @Html.ValidationMessageFor(model => model.password, "", new { @class = "error" })
            </td>
        </tr>
        @*<tr>
            <td>
                Remember Me
            </td>
            <td>
                @Html.CheckBoxFor(m => m.RememberMe)
            </td>
            <td></td>
        </tr>*@
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Submit" />
            </td>
            <td></td>
        </tr>
    </table>
}
@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/jqueryval")